SharedErp/Areas/Inventory/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using SharedErp.Models;
using SharedErp.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SharedErp.Areas.Security.Models;

namespace SharedErp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EmployeeController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public EmployeeController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            await FetchRequiredDropDowns();

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetData(IDataTablesRequest request)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var page = (request.Start / request.Length) + 1;
            var url = string.Format("{0}/{1}/{2}/{3}", Constants.ClientRoutes.Employees,
                page, request.Length, request.Search.Value);

            var result = await client.GetAsync<PagedRecordModel<EmployeeModel>>(url);

            var pagedData = result.Object;

            var response = DataTablesResponse.Create(request, pagedData.Count, pagedData.TotalItemCount, pagedData.Items);
            return new DataTablesJsonResult(response, true);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeModel model)
        {
            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

                var result = await client.PostAsJsonAsync<EmployeeModel, bool>(Constants.ClientRoutes.EmployeeCreate, model);

                if (result.IsValid && result.Object)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    foreach (var item in result.ValidationErrors)
                    {
                        ModelState.AddModelError(item.Key, string.Join(",", item.Value));
                    }

                    ModelState.AddModelError("", result.ShortDescription);
                }
            }
            await FetchRequiredDropDowns(model.RoleId, model.TerminalId);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var url = string.Format(Constants.ClientRoutes.EmployeeGet, id);
            var result = await client.GetAsync<EmployeeModel>(url);

            var model = result.Object;

            if (model != null)
            {
                await FetchRequiredDropDowns(model.RoleId, model.TerminalId);
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, EmployeeModel model)
        {
            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

                var url = string.Format(Constants.ClientRoutes.EmployeeUpdate, id);

                var result = await client.PutAsync<EmployeeModel, bool>(url, model);

                if (result.IsValid && result.Object)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    foreach (var item in result.ValidationErrors)
                    {
                        ModelState.AddModelError(item.Key, string.Join(",", item.Value));
                    }

                    ModelState.AddModelError("", result.ShortDescription);
                }
            }
            await FetchRequiredDropDowns(model.RoleId, model.TerminalId);

            return View(model);
        }

        private async Task FetchRequiredDropDowns(int? selectedRoleId = null, int? selectedTerminalId = null, int? selectedDepartmentId = null)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var stateRequest = await client.GetAsync<PagedRecordModel<RoleModel>>(Constants.ClientRoutes.Roles);
            var terminalRequest = await client.GetAsync<PagedRecordModel<TerminalModel>>(Constants.ClientRoutes.Terminals);

            ViewBag.RoleId = new SelectList(stateRequest.Object.Items, "Id", "Name", selectedRoleId);
            ViewBag.TerminalId = new SelectList(terminalRequest.Object.Items, "Id", "Name", selectedTerminalId);
        }

        public async Task<IActionResult> DeactivateActivate(int Id)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            // var results = await client.PostAsJsonAsync<int, bool>(Constants.ClientRoutes.activateaccount, Id);

            var response = await client.PostAsJsonAsync<int, bool>($"{Constants.ClientRoutes.activateaccount}/{Id}", Id);
            return RedirectToAction("index");
        }
    }
}

SharedErp/Areas/Inventory/Controllers/InventorySetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using SharedErp.Models;
using SharedErp.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SharedErp.Utils.Alerts;
using SharedErp.Areas.Security.Models;
using SharedErp.Areas.Admin.Models;
using SHB.Core.Entities.Enums;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace SharedErp.Areas.Admin.Controllers
{

    [Area("Inventory")]
    public class InventorySetupController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public InventorySetupController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> ItemSetups()
        {
            return View();
        }

        //public async Task<IActionResult> ItemIndex()
        //{
        //    return View();
        //}

        #region Part B

        #region Inventory Items
        [HttpGet]
        public async Task<IActionResult> GetAllInventoryItems(IDataTablesRequest request)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var page = (request.Start / request.Length) + 1;
            var url = string.Format("{0}/{1}/{2}/{3}", Constants.ClientRoutes.InventorySetup,
                page, request.Length, request.Search.Value);

            var result = await client.GetAsync<PagedRecordModel<InventoryItemDTO>>(url);

            var pagedData = result.Object;

            var response = DataTablesResponse.Create(request, pagedData.Count, pagedData.TotalItemCount, pagedData.Items);
            return new DataTablesJsonResult(response, true);
        }



        [HttpGet]
        public async Task<IActionResult> Create()
        {

            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var itemType = await client.GetAsync<PagedRecordModel<ItemTypeDTO>>(Constants.ClientRoutes.InventorySetupItemType);
            var itemCategory = await client.GetAsync<PagedRecordModel<ItemCategoryDTO>>(Constants.ClientRoutes.InventorySetupCategory);
            var itemFamily = await client.GetAsync<PagedRecordModel<ItemFamilyDTO>>(Constants.ClientRoutes.InventorySetupFamilies);
            var wareHouse = await client.GetAsync<PagedRecordModel<WarehouseDTO>>(Constants.ClientRoutes.InventorySetupWarehouse);
            var wareHouseBin = await client.GetAsync<PagedRecordModel<WarehouseBinDTO>>(Constants.ClientRoutes.InventorySetupWarehouseBin);
            var itemSales = await client.GetAsync<PagedRecordModel<InventoryGeneralLedgerChartOfAccountDTO>>(Constants.ClientRoutes.InventorySetupGeneralLedger);
            var vendors = await client.GetAsync<PagedRecordModel<VendorInformationModel>>(Constants.ClientRoutes.VendorInfos);

            var unique = itemType?.Object?.Items;
            var InventoryCategory = itemCategory?.Object?.Items;
            var InventoryFamily = itemFamily?.Object?.Items;
            var itemWareHouse = wareHouse?.Object?.Items;
            var itemWareHouseBin = wareHouseBin?.Object?.Items;
            var salesAccount = itemSales?.Object?.Items;
            var vendor = vendors?.Object?.Items;


            ViewData["ItemTypelist"] = new SelectList(unique, "Id", "ItemTypeName");
            ViewData["InventoryCategory"] = new SelectList(InventoryCategory, "Id", "CategoryName");
            ViewData["InventoryFamily"] = new SelectList(InventoryFamily, "Id", "FamilyDescription");
            ViewData["ItemWareHouse"] = new SelectList(itemWareHouse, "Id", "WarehouseName");
            ViewData["ItemWareHouseBin"] = new SelectList(itemWareHouseBin, "Id", "WarehouseBinName");
            ViewData["ItemSalesAccount"] = new SelectList(salesAccount, "Id", "CGLAccountNumber");
            ViewData["ItemCOGSAccount"] = new SelectList(salesAccount, "Id", "CGLAccountNumber");
            ViewData["ItemInventoryAccount"] = new SelectList(salesAccount, "Id", "CGLAccountNumber");
            ViewData["Vendors"] = new SelectList(vendor, "Id", "VendorName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InventoryItemDTO model)
        {


            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

                var result = await client.PostAsJsonAsync<InventoryItemDTO, bool>(Constants.ClientRoutes.InventorySetupCreate, model);



                if (result.IsValid && result.Object)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    foreach (var item in result.ValidationErrors)
                    {
                        ModelState.AddModelError(item.Key, string.Join(",", item.Value));
                    }

                    ModelState.AddModelError("", result.ShortDescription);
                }

            }

            return View(model);

        }

        public async Task<IActionResult> InventoryItemSave(int Id, string Code, string Name, string Description)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);
            InventoryItemDTO model = null;
            IServiceResponse<bool> response = null;
            bool item = false;

            model = new InventoryItemDTO
            {
                Id = Id,
                ItemCode = Code,
                ItemName = Name,
                itemDescription = Description,
                //GLAccountType = Type
                //WarehouseID = 3
                //TransactionDate = TransDate.GetValueOrDefault()
            };

            if (Id == 0)
            {
                // Do save to database
                response = await client.PostAsJsonAsync<InventoryItemDTO, bool>(Constants.ClientRoutes.InventorySetupCreate, model);
                item = response.Object;

                if (response.ValidationErrors.Count > 0)
                {
                    return View(item).WithWarning(response.Code + ": " + response.ShortDescription);
                }
            }
            else
            {
                // Do Update to database
                var url = string.Format(Constants.ClientRoutes.InventorySetupUpdate, Id);
                var result = await client.PutAsync<InventoryItemDTO, bool>(url, model);
                item = result.Object;

                if (result.ValidationErrors.Count > 0)
                {
                    return View(item).WithWarning(response.Code + ": " + response.ShortDescription);
                }
            }

            return RedirectToAction("index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

            var itemType = await client.GetAsync<PagedRecordModel<ItemTypeDTO>>(Constants.ClientRoutes.InventorySetupItemType);
            var itemCategory = await client.GetAsync<PagedRecordModel<ItemCategoryDTO>>(Constants.ClientRoutes.InventorySetupCategory);
            var itemFamily = await client.GetAsync<PagedRecordModel<ItemFamilyDTO>>(Constants.ClientRoutes.InventorySetupFamilies);
            var wareHouse = await client.GetAsync<PagedRecordModel<WarehouseDTO>>(Constants.ClientRoutes.InventorySetupWarehouse);
            var wareHouseBin = await client.GetAsync<PagedRecordModel<WarehouseBinDTO>>(Constants.ClientRoutes.InventorySetupWarehouseBin);
            var itemSales = await client.GetAsync<PagedRecordModel<InventoryGeneralLedgerChartOfAccountDTO>>(Constants.ClientRoutes.InventorySetupGeneralLedger);

            var ItemType = itemType?.Object?.Items;
            var InventoryCategory = itemCategory?.Object?.Items;
            var InventoryFamily = itemFamily?.Object?.Items;
            var itemWareHouse = wareHouse?.Object?.Items;
            var itemWareHouseBin = wareHouseBin?.Object?.Items;
            var salesAccount = itemSales?.Object?.Items;

            ViewData["ItemTypelist"] = new SelectList(ItemType, "Id", "ItemTypeName");
            ViewData["InventoryCategory"] = new SelectList(InventoryCategory, "Id", "CategoryName");
            ViewData["InventoryFamily"] = new SelectList(InventoryFamily, "Id", "FamilyDescription");
            ViewData["ItemWareHouse"] = new SelectList(itemWareHouse, "Id", "WarehouseName");
            ViewData["ItemWareHouseBin"] = new SelectList(itemWareHouseBin, "Id", "WarehouseBinName");
            ViewData["ItemSalesAccount"] = new SelectList(salesAccount, "Id", "CGLAccountNumber");
            ViewData["ItemCOGSAccount"] = new SelectList(salesAccount, "Id", "CGLAccountNumber");
            ViewData["ItemInventoryAccount"] = new SelectList(salesAccount, "Id", "CGLAccountNumber");


            var url = string.Format(Constants.ClientRoutes.InventorySetupGet, id);
            var result = await client.GetAsync<InventoryItemDTO>(url);

            var model = result.Object;

            if (model != null)
            {
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, InventoryItemDTO model)
        {
            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient(Constants.ClientWithToken);

                var url = string.Format(Constants.ClientRoutes.InventorySetupUpdate, id);

                var result = await client.PutAsync<InventoryItemDTO, bool>(url, model);

SharedErp/Areas/Inventory/Views/InventorySetup/EmployeesCreate.cshtml
@model SharedErp.Models.EmployeeModel
@{
    ViewData["Title"] = "Create Employee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var Code = "EMP-" + Guid.NewGuid().ToString("n").Substring(0, 3).ToUpper();
}

<!--begin::Form-->
@*<form action="EmployeesCreate" method="post">*@
    <form action="EmployeesCreate" method="post" enctype="multipart/form-data" id="form" name="form">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor">
            <!-- begin:: Content Head -->
            <div class="kt-subheader   kt-grid__item" id="kt_subheader">
                <div class="kt-subheader__main">

                    <h3 class="kt-subheader__title">
                        Create Employee
                    </h3>

                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>

                    <div class="kt-subheader__group" id="kt_subheader_search">
                        <span class="kt-subheader__desc" id="kt_subheader_total">
                            Alex Stone
                        </span>

                    </div>

                </div>

                <div class="kt-subheader__toolbar">

                    <a href="~/Inventory/InventorySetup/EmployeesIndex" class="btn btn-default btn-bold">
                        Back
                    </a>

                    <div class="btn-group">
                        <button type="submit" class="btn btn-brand btn-bold">

                            Save Changes
                        </button>
                        <button type="button" class="btn btn-brand btn-bold dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        </button>
                        <input type="button" class="btn btn-secondary" value="Cancel" onclick="@("window.location.href='" + @Url.Action("EmployeesIndex", "inventorysetup") + "'");" />
                        <div class="dropdown-menu dropdown-menu-right">
                            <ul class="kt-nav">
                                <li class="kt-nav__item">
                                    <a href="#" class="kt-nav__link">
                                        <i class="kt-nav__link-icon flaticon2-writing"></i>
                                        <span class="kt-nav__link-text">Save &amp; continue</span>
                                    </a>
                                </li>
                                <li class="kt-nav__item">
                                    <a href="#" class="kt-nav__link">
                                        <i class="kt-nav__link-icon flaticon2-medical-records"></i>
                                        <span class="kt-nav__link-text">Save &amp; add new</span>
                                    </a>
                                </li>
                                <li class="kt-nav__item">
                                    <a href="#" class="kt-nav__link">
                                        <i class="kt-nav__link-icon flaticon2-hourglass-1"></i>
                                        <span class="kt-nav__link-text">Save &amp; exit</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
            <!-- end:: Content Head -->										<!-- begin:: Content -->
            <!-- begin:: Content -->
            <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
                <div class="kt-portlet kt-portlet--tabs">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-toolbar">
                            <ul class="nav nav-tabs nav-tabs-space-xl nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#kt_apps_user_edit_tab_1" role="tab">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <polygon id="Bound" points="0 0 24 0 24 24 0 24" />
                                                <path d="M12.9336061,16.072447 L19.36,10.9564761 L19.5181585,10.8312381 C20.1676248,10.3169571 20.2772143,9.3735535 19.7629333,8.72408713 C19.6917232,8.63415859 19.6104327,8.55269514 19.5206557,8.48129411 L12.9336854,3.24257445 C12.3871201,2.80788259 11.6128799,2.80788259 11.0663146,3.24257445 L4.47482784,8.48488609 C3.82645598,9.00054628 3.71887192,9.94418071 4.23453211,10.5925526 C4.30500305,10.6811601 4.38527899,10.7615046 4.47382636,10.8320511 L4.63,10.9564761 L11.0659024,16.0730648 C11.6126744,16.5077525 12.3871218,16.5074963 12.9336061,16.072447 Z" id="Shape" fill="#000000" fill-rule="nonzero" />
                                                <path d="M11.0563554,18.6706981 L5.33593024,14.122919 C4.94553994,13.8125559 4.37746707,13.8774308 4.06710397,14.2678211 C4.06471678,14.2708238 4.06234874,14.2738418 4.06,14.2768747 L4.06,14.2768747 C3.75257288,14.6738539 3.82516916,15.244888 4.22214834,15.5523151 C4.22358765,15.5534297 4.2250303,15.55454 4.22647627,15.555646 L11.0872776,20.8031356 C11.6250734,21.2144692 12.371757,21.2145375 12.909628,20.8033023 L19.7677785,15.559828 C20.1693192,15.2528257 20.2459576,14.6784381 19.9389553,14.2768974 C19.9376429,14.2751809 19.9363245,14.2734691 19.935,14.2717619 L19.935,14.2717619 C19.6266937,13.8743807 19.0546209,13.8021712 18.6572397,14.1104775 C18.654352,14.112718 18.6514778,14.1149757 18.6486172,14.1172508 L12.9235044,18.6705218 C12.377022,19.1051477 11.6029199,19.1052208 11.0563554,18.6706981 Z" id="Path" fill="#000000" opacity="0.3" />
                                            </g>
                                        </svg>                        Main
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </div>

                    <div class="kt-portlet__body">


                        @Html.AntiForgeryToken()
                        @Html.Partial("Employeesform")

                    </div>
                </div>
            </div>
            <!-- end:: Content -->					<!-- end:: Content -->
        </div>

    </form>


    <!--end::Form-->
    @section scripts{
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        <script>

        var BootstrapDatepicker = function () {
            var t;
            t = mUtil.isRTL() ? {
                leftArrow: '<i class="la la-angle-right"></i>',
                rightArrow: '<i class="la la-angle-left"></i>'
            } : {
                    leftArrow: '<i class="la la-angle-left"></i>',
                    rightArrow: '<i class="la la-angle-right"></i>'
                };
            return {
                init: function () {
                    $("#IsParentDate,#PilotPayrollDate").datepicker({
                        rtl: mUtil.isRTL(),
                        autoclose: !0,
                        todayHighlight: !0,
                        orientation: "bottom left",
                        templates: t,
                        format: "D, dd MM yyyy"
                    });
                    $("#TerminalId, #RoleId, #Gender").select2({
                        placeholder: "Select"
                    })
                }
            }
        }();

        jQuery(document).ready(function () {
            BootstrapDatepicker.init();
            $('.dropdown-select2').select2();
            DropRoles.init();
            DropTerminal.init();
        });



        var ctt = null;

       var DropRoles = {
           init: function (ctt) {
               $.get('@Url.Action("FetchDetailDropDown", "InventorySetup")?dropdesc=' + "RoleList",
                    function (response) {
                        var availabledata = response.data;
                        //$("#ItemDefaultWarehouseID")
                        for (var i = 0; i < availabledata.length; i++) {
                            $("#RoleId").append(new Option(availabledata[i].text, availabledata[i].value));

                        }
                        $(ctt).select2({
                            placeholder: "Select.. option"
                        });
                    });
            }
        }

             var DropTerminal = {
           init: function (ctt) {
                     $.get('@Url.Action("FetchDetailDropDown", "InventorySetup")?dropdesc=' + "TerminalList",
                    function (response) {
                        var availabledata = response.data;
                        //$("#ItemDefaultWarehouseID")
                        for (var i = 0; i < availabledata.length; i++) {
                            $("#TerminalId").append(new Option(availabledata[i].text, availabledata[i].value));

                        }
                        $(ctt).select2({
                            placeholder: "Select.. option"
                        });
                    });
            }
        }


        </script>


    }